url: https://dk487.github.io
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page

lang: en
title: FIXME
description: FIXME
